### ISSUE TITLE
NullException on loading cover

### ISSUE THREAD

**Issue by admarcel** [eltoncezar/Spofy#12]
Hello, 

When i'm launching Spofy from Visual studio, the app crash with a NullException.

Spofy can't load the AlbumArt from `SpotifyManager.cs` at line 178.

``` c#
_currentLargeCover = await _currentTrack.GetAlbumArtAsync(AlbumArtSize.Size640);
_currentSmallCoverUrl = _currentTrack.GetAlbumArtUrl(AlbumArtSize.Size160);
```

To get spofy running, if have to check if `currentLargeCover` is null

``` c#
if(_currentLargeCover)
            model.Image = _currentLargeCover;
}
```

At this moment, I can pass to next song and get title.

Is it a problem linked with my computer ? fresh install of win 10 Spotify version 1.0.25.127.g58007b4c ? 
Can it be a problem from SpotifyAPI-NET ? 
spofy cloned from master.

Thank you

**Comment by eltoncezar** [comment]
Hi,

Indeed, this is a strange behavior. Could you please tell me what Visual Studio and Windows version are you using? Will look into it.

**Comment by admarcel** [comment]
Windows 10 and Visual studio 2015

**Comment by admarcel** [comment]
I just try the example of SpotifyAPI-NET, this can't load the art too.
<img width="246" alt="capture" src="https://cloud.githubusercontent.com/assets/2989637/14191361/c9596876-f797-11e5-85e1-bf614aac0ea1.PNG">

**Comment by eltoncezar** [comment]
After all, there was a change in Spotify's side, so just updating the SpotifyAPI-NET dll fixed it.
Thanks for the PR, @admarcel!
