### ISSUE TITLE
The app needs to update the SpotifyAPI-NET vesion.

### ISSUE THREAD

**Issue by manuelex20** [eltoncezar/Spofy#19]
I had a problem when the app try to get the album image and gave a null reference. Just appling Install-Package SpotifyAPI-NET, I fixed the problem.
[Spofy-master.zip](https://github.com/eltoncezar/Spofy/files/1348123/Spofy-master.zip)

**Comment by c15c** [comment]
Hey manuelex20, 

How do I apply Install-Package SpotifyAPI-NET

**Comment by c15c** [comment]
Hey @manuelex20 

How do I apply the Install-Package SpotifyAPI-NET?

**Comment by manuelex20** [comment]
Select the project and choose in the toolbar: 
Tools/ Library package manager /Package manager console.
Idk if the words are exactly cause I'm spanish talker and I'm translating it.
You can write me if you want to my mail: manuelex20@gmail.com if you need help.
However, don't forget to search in Google first.
Blesses.

**Comment by camjac251** [comment]
Do you happen to have a compiled version available?

**Comment by eltoncezar** [comment]
Hi folks! Sorry about my late reply. I've updated the repo with the lastest version of SpotifyAPI-NET as of this moment. Everything should work by now. I'll also add a new release with this update.

Many many thanks for your support!
