### ISSUE TITLE
How do I execute it?

### ISSUE THREAD

**Issue by visualcookie** [eltoncezar/Spofy#5]
Hi,

I recently discovered your application and I wanted to give it a try... but I have no idea how to execute it since there are only working files and no executable.

**Comment by eltoncezar** [comment]
Hi, sorry about that. I included the executable in the releases page. You can download it from there, or from [here](https://github.com/eltoncezar/Spofy/releases/download/v0.2-alpha/Spofy.exe).
Thanks for pointing me that, and I am willing to receive your feedback!
